/**
 * Onion Loader for Cursor IDE
 * Auto-generated by @onion/cli v4.0.0-beta.1
 * 
 * Descobre e sincroniza recursos do Sistema Onion para o Cursor IDE
 */
const fs = require('fs');
const path = require('path');
const yaml = require('yaml');

class CursorOnionLoader {
  constructor(projectRoot) {
    this.projectRoot = projectRoot || path.join(__dirname, '../../../');
    this.onionRoot = path.join(this.projectRoot, '.onion');
    this.cursorRoot = path.join(this.projectRoot, '.cursor');
    this.config = null;
    this.watchers = [];
  }
  
  /**
   * Carrega configuração .onion-config.yml
   */
  loadConfig() {
    const configPath = path.join(this.projectRoot, '.onion-config.yml');
    if (!fs.existsSync(configPath)) {
      throw new Error('❌ .onion-config.yml not found');
    }
    this.config = yaml.parse(fs.readFileSync(configPath, 'utf-8'));
    return this.config;
  }
  
  /**
   * Descobre contextos disponíveis
   */
  discoverContexts() {
    const contextsDir = path.join(this.onionRoot, 'contexts');
    if (!fs.existsSync(contextsDir)) {
      return [];
    }
    
    return fs.readdirSync(contextsDir).filter(name => {
      const contextPath = path.join(contextsDir, name);
      return fs.statSync(contextPath).isDirectory();
    });
  }
  
  /**
   * Descobre comandos por contexto e nível
   */
  discoverCommands(context, level = null) {
    const commands = [];
    const contextCommandsDir = path.join(this.onionRoot, 'contexts', context, 'commands');
    
    if (!fs.existsSync(contextCommandsDir)) {
      return commands;
    }
    
    // Se nível especificado, buscar apenas naquele nível
    if (level) {
      const levelDir = path.join(contextCommandsDir, level);
      if (fs.existsSync(levelDir)) {
        const files = fs.readdirSync(levelDir);
        files.forEach(file => {
          if (file.endsWith('.md')) {
            commands.push({
              name: file.replace('.md', ''),
              path: path.join(levelDir, file),
              context,
              level,
              relativePath: path.relative(this.projectRoot, path.join(levelDir, file))
            });
          }
        });
      }
    } else {
      // Buscar em todos os níveis
      const levels = ['starter', 'intermediate', 'advanced'];
      levels.forEach(lvl => {
        const levelDir = path.join(contextCommandsDir, lvl);
        if (fs.existsSync(levelDir)) {
          const files = fs.readdirSync(levelDir);
          files.forEach(file => {
            if (file.endsWith('.md')) {
              commands.push({
                name: file.replace('.md', ''),
                path: path.join(levelDir, file),
                context,
                level: lvl,
                relativePath: path.relative(this.projectRoot, path.join(levelDir, file))
              });
            }
          });
        }
      });
      
      // Comandos na raiz do contexto (ex: help.md)
      const rootFiles = fs.readdirSync(contextCommandsDir);
      rootFiles.forEach(file => {
        const filePath = path.join(contextCommandsDir, file);
        if (fs.statSync(filePath).isFile() && file.endsWith('.md')) {
          commands.push({
            name: file.replace('.md', ''),
            path: filePath,
            context,
            level: 'root',
            relativePath: path.relative(this.projectRoot, filePath)
          });
        }
      });
    }
    
    return commands;
  }
  
  /**
   * Descobre agentes por contexto
   */
  discoverAgents(context) {
    const agents = [];
    const contextAgentsDir = path.join(this.onionRoot, 'contexts', context, 'agents');
    
    if (!fs.existsSync(contextAgentsDir)) {
      return agents;
    }
    
    const files = fs.readdirSync(contextAgentsDir);
    files.forEach(file => {
      if (file.endsWith('.md')) {
        agents.push({
          name: file.replace('.md', ''),
          path: path.join(contextAgentsDir, file),
          context,
          relativePath: path.relative(this.projectRoot, path.join(contextAgentsDir, file))
        });
      }
    });
    
    return agents;
  }
  
  /**
   * Descobre comandos core
   */
  discoverCoreCommands() {
    const commands = [];
    const coreCommandsDir = path.join(this.onionRoot, 'core', 'commands');
    
    if (!fs.existsSync(coreCommandsDir)) {
      return commands;
    }
    
    const files = fs.readdirSync(coreCommandsDir);
    files.forEach(file => {
      if (file.endsWith('.md')) {
        commands.push({
          name: file.replace('.md', ''),
          path: path.join(coreCommandsDir, file),
          context: 'core',
          level: 'core',
          relativePath: path.relative(this.projectRoot, path.join(coreCommandsDir, file))
        });
      }
    });
    
    return commands;
  }
  
  /**
   * Descobre agentes core
   */
  discoverCoreAgents() {
    const agents = [];
    const coreAgentsDir = path.join(this.onionRoot, 'core', 'agents');
    
    if (!fs.existsSync(coreAgentsDir)) {
      return agents;
    }
    
    const files = fs.readdirSync(coreAgentsDir);
    files.forEach(file => {
      if (file.endsWith('.md')) {
        agents.push({
          name: file.replace('.md', ''),
          path: path.join(coreAgentsDir, file),
          context: 'core',
          relativePath: path.relative(this.projectRoot, path.join(coreAgentsDir, file))
        });
      }
    });
    
    return agents;
  }
  
  /**
   * Descobre todos os recursos
   */
  discover() {
    if (!this.config) {
      this.loadConfig();
    }
    
    const contexts = this.discoverContexts();
    const commands = [];
    const agents = [];
    
    // Comandos e agentes core
    commands.push(...this.discoverCoreCommands());
    agents.push(...this.discoverCoreAgents());
    
    // Comandos e agentes por contexto
    contexts.forEach(context => {
      commands.push(...this.discoverCommands(context));
      agents.push(...this.discoverAgents(context));
    });
    
    return {
      config: this.config,
      contexts,
      commands,
      agents
    };
  }
  
  /**
   * Cria symlink se não existir
   */
  createSymlink(target, linkPath) {
    const linkDir = path.dirname(linkPath);
    
    // Criar diretório se não existir
    if (!fs.existsSync(linkDir)) {
      fs.mkdirSync(linkDir, { recursive: true });
    }
    
    // Remover link existente se for diferente
    if (fs.existsSync(linkPath)) {
      try {
        const existingTarget = fs.readlinkSync(linkPath);
        if (existingTarget !== target) {
          fs.unlinkSync(linkPath);
        } else {
          return; // Já existe e aponta para o lugar certo
        }
      } catch (err) {
        // Não é symlink, remover arquivo
        fs.unlinkSync(linkPath);
      }
    }
    
    // Criar symlink
    try {
      fs.symlinkSync(target, linkPath, 'file');
    } catch (err) {
      // Em Windows, pode precisar de permissões administrativas
      console.warn('⚠️  Could not create symlink: ' + linkPath);
      console.warn('   Error: ' + err.message);
    }
  }
  
  /**
   * Sincroniza recursos para .cursor/
   */
  syncToCursor() {
    if (!fs.existsSync(this.cursorRoot)) {
      fs.mkdirSync(this.cursorRoot, { recursive: true });
    }
    
    const resources = this.discover();
    const commandsDir = path.join(this.cursorRoot, 'commands');
    const agentsDir = path.join(this.cursorRoot, 'agents');
    
    fs.mkdirSync(commandsDir, { recursive: true });
    fs.mkdirSync(agentsDir, { recursive: true });
    
    // Sincronizar comandos
    resources.commands.forEach(cmd => {
      const targetPath = path.resolve(this.projectRoot, cmd.relativePath);
      let linkPath;
      
      if (cmd.context === 'core') {
        linkPath = path.join(commandsDir, cmd.name + '.md');
      } else {
        const contextCommandsDir = path.join(commandsDir, cmd.context);
        fs.mkdirSync(contextCommandsDir, { recursive: true });
        linkPath = path.join(contextCommandsDir, cmd.name + '.md');
      }
      
      // Criar symlink relativo
      const relativeTarget = path.relative(path.dirname(linkPath), targetPath);
      this.createSymlink(relativeTarget, linkPath);
    });
    
    // Sincronizar agentes
    resources.agents.forEach(agent => {
      const targetPath = path.resolve(this.projectRoot, agent.relativePath);
      let linkPath;
      
      if (agent.context === 'core') {
        linkPath = path.join(agentsDir, agent.name + '.md');
      } else {
        const contextAgentsDir = path.join(agentsDir, agent.context);
        fs.mkdirSync(contextAgentsDir, { recursive: true });
        linkPath = path.join(contextAgentsDir, agent.name + '.md');
      }
      
      // Criar symlink relativo
      const relativeTarget = path.relative(path.dirname(linkPath), targetPath);
      this.createSymlink(relativeTarget, linkPath);
    });
    
    // Atualizar .cursorrules
    this.updateCursorRules(resources);
    
    return {
      commandsSynced: resources.commands.length,
      agentsSynced: resources.agents.length,
      contexts: resources.contexts
    };
  }
  
  /**
   * Atualiza .cursorrules com informações dos contextos
   */
  updateCursorRules(resources) {
    const cursorRulesPath = path.join(this.cursorRoot, '.cursorrules');
    
    let cursorRulesContent = '# Sistema Onion v4.0\n';
    cursorRulesContent += '# Auto-generated by @onion/cli\n\n';
    cursorRulesContent += 'Este projeto usa o Sistema Onion - Multi-Context Development Orchestrator.\n\n';
    cursorRulesContent += '## Estrutura\n\n';
    cursorRulesContent += '- **Comandos**: .cursor/commands/ (symlinks de .onion/)\n';
    cursorRulesContent += '- **Agentes**: .cursor/agents/ (symlinks de .onion/)\n';
    cursorRulesContent += '- **Fonte**: .onion/\n\n';
    cursorRulesContent += '## Contextos Disponíveis\n\n';
    
    resources.contexts.forEach(ctx => {
      cursorRulesContent += '- **' + ctx + '**: /' + ctx + '/*\n';
    });
    
    cursorRulesContent += '\n## Comandos Principais\n\n';
    
    resources.contexts.forEach(ctx => {
      const contextCommands = resources.commands.filter(c => c.context === ctx);
      const starterCommands = contextCommands.filter(c => c.level === 'starter');
      const ctxName = ctx.charAt(0).toUpperCase() + ctx.slice(1);
      
      cursorRulesContent += '### ' + ctxName + '\n';
      cursorRulesContent += '- /' + ctx + '/help - Ver comandos disponíveis\n';
      if (starterCommands.length > 0) {
        const cmdNames = starterCommands.slice(0, 3).map(c => '/' + ctx + '/' + c.name).join(', ');
        cursorRulesContent += '- Starter commands (' + starterCommands.length + '): ' + cmdNames + '\n';
      }
      cursorRulesContent += '\n';
    });
    
    cursorRulesContent += '## Core Commands\n\n';
    cursorRulesContent += '- /help - Help global do Sistema Onion\n';
    cursorRulesContent += '- /onion - Orquestrador principal\n\n';
    cursorRulesContent += '## Documentação\n\n';
    cursorRulesContent += 'Consulte .onion/README.md ou docs/onion/ para mais informações.\n\n';
    cursorRulesContent += '---\n\n';
    cursorRulesContent += '**Gerado por**: @onion/cli v4.0.0-beta.1\n';
    cursorRulesContent += '**Última atualização**: ' + new Date().toISOString() + '\n';
    
    fs.writeFileSync(cursorRulesPath, cursorRulesContent, 'utf-8');
  }
  
  /**
   * Watch para mudanças em .onion/
   */
  watch() {
    if (!fs.existsSync(this.onionRoot)) {
      return;
    }
    
    // Debounce para evitar múltiplas sincronizações
    let syncTimeout = null;
    const debouncedSync = () => {
      if (syncTimeout) {
        clearTimeout(syncTimeout);
      }
      syncTimeout = setTimeout(() => {
        try {
          this.syncToCursor();
          console.log('🔄 Onion resources synced to Cursor');
        } catch (err) {
          console.error('❌ Error syncing Onion resources:', err.message);
        }
      }, 1000); // 1 segundo de debounce
    };
    
    // Watch recursivo em .onion/
    const watchOptions = { recursive: true };
    
    try {
      const watcher = fs.watch(this.onionRoot, watchOptions, (eventType, filename) => {
        if (filename && (filename.endsWith('.md') || filename.includes('commands') || filename.includes('agents'))) {
          debouncedSync();
        }
      });
      
      this.watchers.push(watcher);
      
      // Watch também em .onion-config.yml
      const configWatcher = fs.watch(
        path.join(this.projectRoot, '.onion-config.yml'),
        (eventType) => {
          if (eventType === 'change') {
            this.loadConfig(); // Recarregar config
            debouncedSync();
          }
        }
      );
      
      this.watchers.push(configWatcher);
      
      console.log('👀 Watching .onion/ for changes...');
    } catch (err) {
      console.warn('⚠️  Could not start file watcher:', err.message);
      console.warn('   Changes will not be synced automatically');
    }
  }
  
  /**
   * Para watch
   */
  stopWatch() {
    this.watchers.forEach(watcher => watcher.close());
    this.watchers = [];
  }
}

// Singleton instance
let loaderInstance = null;

function getLoader(projectRoot) {
  if (!loaderInstance) {
    loaderInstance = new CursorOnionLoader(projectRoot);
  }
  return loaderInstance;
}

// Auto-sync na inicialização se executado diretamente
if (require.main === module) {
  const loader = getLoader();
  loader.syncToCursor();
  console.log('✅ Onion resources synced to Cursor');
  
  // Iniciar watch se --watch flag
  if (process.argv.includes('--watch')) {
    loader.watch();
    
    // Manter processo vivo
    process.on('SIGINT', () => {
      loader.stopWatch();
      process.exit(0);
    });
  }
}

module.exports = { CursorOnionLoader, getLoader };
