/**
 * Gerador de loaders por IDE
 */
const fs = require('fs-extra');
const path = require('path');
const logger = require('../utils/logger');

class LoadersGenerator {
  constructor(projectRoot, config) {
    this.projectRoot = projectRoot;
    this.config = config;
  }
  
  async generate() {
    for (const ide of this.config.ides) {
      if (ide === 'universal') {
        await this.generateUniversalAgentsMd();
      } else {
        await this.generateIDELoader(ide);
        // Criar estrutura na raiz para o IDE reconhecer
        await this.createIDERootStructure(ide);
      }
    }
  }
  
  async generateIDELoader(ide) {
    logger.startSpinner(`Generating ${ide} loader...`);
    
    const loaderPath = path.join(this.projectRoot, '.onion', 'ide', ide);
    await fs.ensureDir(loaderPath);
    
    if (ide === 'cursor') {
      await this.generateCursorLoader(loaderPath);
    } else if (ide === 'windsurf') {
      await this.generateWindsurfLoader(loaderPath);
    } else if (ide === 'claude-code') {
      await this.generateClaudeLoader(loaderPath);
    }
    
    logger.stopSpinner(true, `Created ${ide} loader`);
  }
  
  async generateCursorLoader(loaderPath) {
    const loaderContent = `/**
 * Onion Loader for Cursor IDE
 * Auto-generated by @onion/cli v4.0.0-beta.1
 * 
 * Descobre e sincroniza recursos do Sistema Onion para o Cursor IDE
 */
const fs = require('fs');
const path = require('path');
const yaml = require('yaml');

class CursorOnionLoader {
  constructor(projectRoot) {
    this.projectRoot = projectRoot || path.join(__dirname, '../../../');
    this.onionRoot = path.join(this.projectRoot, '.onion');
    this.cursorRoot = path.join(this.projectRoot, '.cursor');
    this.config = null;
    this.watchers = [];
  }
  
  /**
   * Carrega configuração .onion-config.yml
   */
  loadConfig() {
    const configPath = path.join(this.projectRoot, '.onion-config.yml');
    if (!fs.existsSync(configPath)) {
      throw new Error('❌ .onion-config.yml not found');
    }
    this.config = yaml.parse(fs.readFileSync(configPath, 'utf-8'));
    return this.config;
  }
  
  /**
   * Descobre contextos disponíveis
   */
  discoverContexts() {
    const contextsDir = path.join(this.onionRoot, 'contexts');
    if (!fs.existsSync(contextsDir)) {
      return [];
    }
    
    return fs.readdirSync(contextsDir).filter(name => {
      const contextPath = path.join(contextsDir, name);
      return fs.statSync(contextPath).isDirectory();
    });
  }
  
  /**
   * Descobre comandos por contexto e nível
   */
  discoverCommands(context, level = null) {
    const commands = [];
    const contextCommandsDir = path.join(this.onionRoot, 'contexts', context, 'commands');
    
    if (!fs.existsSync(contextCommandsDir)) {
      return commands;
    }
    
    // Se nível especificado, buscar apenas naquele nível
    if (level) {
      const levelDir = path.join(contextCommandsDir, level);
      if (fs.existsSync(levelDir)) {
        const files = fs.readdirSync(levelDir);
        files.forEach(file => {
          if (file.endsWith('.md')) {
            commands.push({
              name: file.replace('.md', ''),
              path: path.join(levelDir, file),
              context,
              level,
              relativePath: path.relative(this.projectRoot, path.join(levelDir, file))
            });
          }
        });
      }
    } else {
      // Buscar em todos os níveis
      const levels = ['starter', 'intermediate', 'advanced'];
      levels.forEach(lvl => {
        const levelDir = path.join(contextCommandsDir, lvl);
        if (fs.existsSync(levelDir)) {
          const files = fs.readdirSync(levelDir);
          files.forEach(file => {
            if (file.endsWith('.md')) {
              commands.push({
                name: file.replace('.md', ''),
                path: path.join(levelDir, file),
                context,
                level: lvl,
                relativePath: path.relative(this.projectRoot, path.join(levelDir, file))
              });
            }
          });
        }
      });
      
      // Comandos na raiz do contexto (ex: help.md)
      const rootFiles = fs.readdirSync(contextCommandsDir);
      rootFiles.forEach(file => {
        const filePath = path.join(contextCommandsDir, file);
        if (fs.statSync(filePath).isFile() && file.endsWith('.md')) {
          commands.push({
            name: file.replace('.md', ''),
            path: filePath,
            context,
            level: 'root',
            relativePath: path.relative(this.projectRoot, filePath)
          });
        }
      });
    }
    
    return commands;
  }
  
  /**
   * Descobre agentes por contexto
   */
  discoverAgents(context) {
    const agents = [];
    const contextAgentsDir = path.join(this.onionRoot, 'contexts', context, 'agents');
    
    if (!fs.existsSync(contextAgentsDir)) {
      return agents;
    }
    
    const files = fs.readdirSync(contextAgentsDir);
    files.forEach(file => {
      if (file.endsWith('.md')) {
        agents.push({
          name: file.replace('.md', ''),
          path: path.join(contextAgentsDir, file),
          context,
          relativePath: path.relative(this.projectRoot, path.join(contextAgentsDir, file))
        });
      }
    });
    
    return agents;
  }
  
  /**
   * Descobre comandos core
   */
  discoverCoreCommands() {
    const commands = [];
    const coreCommandsDir = path.join(this.onionRoot, 'core', 'commands');
    
    if (!fs.existsSync(coreCommandsDir)) {
      return commands;
    }
    
    const files = fs.readdirSync(coreCommandsDir);
    files.forEach(file => {
      if (file.endsWith('.md')) {
        commands.push({
          name: file.replace('.md', ''),
          path: path.join(coreCommandsDir, file),
          context: 'core',
          level: 'core',
          relativePath: path.relative(this.projectRoot, path.join(coreCommandsDir, file))
        });
      }
    });
    
    return commands;
  }
  
  /**
   * Descobre agentes core
   */
  discoverCoreAgents() {
    const agents = [];
    const coreAgentsDir = path.join(this.onionRoot, 'core', 'agents');
    
    if (!fs.existsSync(coreAgentsDir)) {
      return agents;
    }
    
    const files = fs.readdirSync(coreAgentsDir);
    files.forEach(file => {
      if (file.endsWith('.md')) {
        agents.push({
          name: file.replace('.md', ''),
          path: path.join(coreAgentsDir, file),
          context: 'core',
          relativePath: path.relative(this.projectRoot, path.join(coreAgentsDir, file))
        });
      }
    });
    
    return agents;
  }
  
  /**
   * Descobre todos os recursos
   */
  discover() {
    if (!this.config) {
      this.loadConfig();
    }
    
    const contexts = this.discoverContexts();
    const commands = [];
    const agents = [];
    
    // Comandos e agentes core
    commands.push(...this.discoverCoreCommands());
    agents.push(...this.discoverCoreAgents());
    
    // Comandos e agentes por contexto
    contexts.forEach(context => {
      commands.push(...this.discoverCommands(context));
      agents.push(...this.discoverAgents(context));
    });
    
    return {
      config: this.config,
      contexts,
      commands,
      agents
    };
  }
  
  /**
   * Cria symlink se não existir
   */
  createSymlink(target, linkPath) {
    const linkDir = path.dirname(linkPath);
    
    // Criar diretório se não existir
    if (!fs.existsSync(linkDir)) {
      fs.mkdirSync(linkDir, { recursive: true });
    }
    
    // Remover link existente se for diferente
    if (fs.existsSync(linkPath)) {
      try {
        const existingTarget = fs.readlinkSync(linkPath);
        if (existingTarget !== target) {
          fs.unlinkSync(linkPath);
        } else {
          return; // Já existe e aponta para o lugar certo
        }
      } catch (err) {
        // Não é symlink, remover arquivo
        fs.unlinkSync(linkPath);
      }
    }
    
    // Criar symlink
    try {
      fs.symlinkSync(target, linkPath, 'file');
    } catch (err) {
      // Em Windows, pode precisar de permissões administrativas
      console.warn('⚠️  Could not create symlink: ' + linkPath);
      console.warn('   Error: ' + err.message);
    }
  }
  
  /**
   * Sincroniza recursos para .cursor/
   */
  syncToCursor() {
    if (!fs.existsSync(this.cursorRoot)) {
      fs.mkdirSync(this.cursorRoot, { recursive: true });
    }
    
    const resources = this.discover();
    const commandsDir = path.join(this.cursorRoot, 'commands');
    const agentsDir = path.join(this.cursorRoot, 'agents');
    
    fs.mkdirSync(commandsDir, { recursive: true });
    fs.mkdirSync(agentsDir, { recursive: true });
    
    // Sincronizar comandos
    resources.commands.forEach(cmd => {
      const targetPath = path.resolve(this.projectRoot, cmd.relativePath);
      let linkPath;
      
      if (cmd.context === 'core') {
        linkPath = path.join(commandsDir, cmd.name + '.md');
      } else {
        const contextCommandsDir = path.join(commandsDir, cmd.context);
        fs.mkdirSync(contextCommandsDir, { recursive: true });
        linkPath = path.join(contextCommandsDir, cmd.name + '.md');
      }
      
      // Criar symlink relativo
      const relativeTarget = path.relative(path.dirname(linkPath), targetPath);
      this.createSymlink(relativeTarget, linkPath);
    });
    
    // Sincronizar agentes
    resources.agents.forEach(agent => {
      const targetPath = path.resolve(this.projectRoot, agent.relativePath);
      let linkPath;
      
      if (agent.context === 'core') {
        linkPath = path.join(agentsDir, agent.name + '.md');
      } else {
        const contextAgentsDir = path.join(agentsDir, agent.context);
        fs.mkdirSync(contextAgentsDir, { recursive: true });
        linkPath = path.join(contextAgentsDir, agent.name + '.md');
      }
      
      // Criar symlink relativo
      const relativeTarget = path.relative(path.dirname(linkPath), targetPath);
      this.createSymlink(relativeTarget, linkPath);
    });
    
    // Atualizar .cursorrules
    this.updateCursorRules(resources);
    
    return {
      commandsSynced: resources.commands.length,
      agentsSynced: resources.agents.length,
      contexts: resources.contexts
    };
  }
  
  /**
   * Atualiza .cursorrules com informações dos contextos
   */
  updateCursorRules(resources) {
    const cursorRulesPath = path.join(this.cursorRoot, '.cursorrules');
    
    let cursorRulesContent = '# Sistema Onion v4.0\\n';
    cursorRulesContent += '# Auto-generated by @onion/cli\\n\\n';
    cursorRulesContent += 'Este projeto usa o Sistema Onion - Multi-Context Development Orchestrator.\\n\\n';
    cursorRulesContent += '## Estrutura\\n\\n';
    cursorRulesContent += '- **Comandos**: .cursor/commands/ (symlinks de .onion/)\\n';
    cursorRulesContent += '- **Agentes**: .cursor/agents/ (symlinks de .onion/)\\n';
    cursorRulesContent += '- **Fonte**: .onion/\\n\\n';
    cursorRulesContent += '## Contextos Disponíveis\\n\\n';
    
    resources.contexts.forEach(ctx => {
      cursorRulesContent += '- **' + ctx + '**: /' + ctx + '/*\\n';
    });
    
    cursorRulesContent += '\\n## Comandos Principais\\n\\n';
    
    resources.contexts.forEach(ctx => {
      const contextCommands = resources.commands.filter(c => c.context === ctx);
      const starterCommands = contextCommands.filter(c => c.level === 'starter');
      const ctxName = ctx.charAt(0).toUpperCase() + ctx.slice(1);
      
      cursorRulesContent += '### ' + ctxName + '\\n';
      cursorRulesContent += '- /' + ctx + '/help - Ver comandos disponíveis\\n';
      if (starterCommands.length > 0) {
        const cmdNames = starterCommands.slice(0, 3).map(c => '/' + ctx + '/' + c.name).join(', ');
        cursorRulesContent += '- Starter commands (' + starterCommands.length + '): ' + cmdNames + '\\n';
      }
      cursorRulesContent += '\\n';
    });
    
    cursorRulesContent += '## Core Commands\\n\\n';
    cursorRulesContent += '- /help - Help global do Sistema Onion\\n';
    cursorRulesContent += '- /onion - Orquestrador principal\\n\\n';
    cursorRulesContent += '## Documentação\\n\\n';
    cursorRulesContent += 'Consulte .onion/README.md ou docs/onion/ para mais informações.\\n\\n';
    cursorRulesContent += '---\\n\\n';
    cursorRulesContent += '**Gerado por**: @onion/cli v4.0.0-beta.1\\n';
    cursorRulesContent += '**Última atualização**: ' + new Date().toISOString() + '\\n';
    
    fs.writeFileSync(cursorRulesPath, cursorRulesContent, 'utf-8');
  }
  
  /**
   * Watch para mudanças em .onion/
   */
  watch() {
    if (!fs.existsSync(this.onionRoot)) {
      return;
    }
    
    // Debounce para evitar múltiplas sincronizações
    let syncTimeout = null;
    const debouncedSync = () => {
      if (syncTimeout) {
        clearTimeout(syncTimeout);
      }
      syncTimeout = setTimeout(() => {
        try {
          this.syncToCursor();
          console.log('🔄 Onion resources synced to Cursor');
        } catch (err) {
          console.error('❌ Error syncing Onion resources:', err.message);
        }
      }, 1000); // 1 segundo de debounce
    };
    
    // Watch recursivo em .onion/
    const watchOptions = { recursive: true };
    
    try {
      const watcher = fs.watch(this.onionRoot, watchOptions, (eventType, filename) => {
        if (filename && (filename.endsWith('.md') || filename.includes('commands') || filename.includes('agents'))) {
          debouncedSync();
        }
      });
      
      this.watchers.push(watcher);
      
      // Watch também em .onion-config.yml
      const configWatcher = fs.watch(
        path.join(this.projectRoot, '.onion-config.yml'),
        (eventType) => {
          if (eventType === 'change') {
            this.loadConfig(); // Recarregar config
            debouncedSync();
          }
        }
      );
      
      this.watchers.push(configWatcher);
      
      console.log('👀 Watching .onion/ for changes...');
    } catch (err) {
      console.warn('⚠️  Could not start file watcher:', err.message);
      console.warn('   Changes will not be synced automatically');
    }
  }
  
  /**
   * Para watch
   */
  stopWatch() {
    this.watchers.forEach(watcher => watcher.close());
    this.watchers = [];
  }
}

// Singleton instance
let loaderInstance = null;

function getLoader(projectRoot) {
  if (!loaderInstance) {
    loaderInstance = new CursorOnionLoader(projectRoot);
  }
  return loaderInstance;
}

// Auto-sync na inicialização se executado diretamente
if (require.main === module) {
  const loader = getLoader();
  loader.syncToCursor();
  console.log('✅ Onion resources synced to Cursor');
  
  // Iniciar watch se --watch flag
  if (process.argv.includes('--watch')) {
    loader.watch();
    
    // Manter processo vivo
    process.on('SIGINT', () => {
      loader.stopWatch();
      process.exit(0);
    });
  }
}

module.exports = { CursorOnionLoader, getLoader };
`;
    
    await fs.writeFile(
      path.join(loaderPath, 'onion-loader.js'),
      loaderContent,
      'utf-8'
    );
    
    // Settings.json
    const settings = {
      'onion': {
        'enabled': true,
        'root': '.onion',
        'loader': '.onion/ide/cursor/onion-loader.js',
        'version': '4.0.0-beta.1'
      }
    };
    
    await fs.writeJson(
      path.join(loaderPath, 'settings.json'),
      settings,
      { spaces: 2 }
    );
    
    // Executar loader para sincronizar imediatamente
    try {
      const { getLoader } = require(path.join(loaderPath, 'onion-loader.js'));
      const loader = getLoader(this.projectRoot);
      const result = loader.syncToCursor();
      logger.info('   Synced ' + result.commandsSynced + ' commands and ' + result.agentsSynced + ' agents');
    } catch (err) {
      logger.warn('   Could not sync immediately: ' + err.message);
      logger.info('   Run manually: node .onion/ide/cursor/onion-loader.js');
    }
  }
  
  async generateWindsurfLoader(loaderPath) {
    logger.startSpinner('Generating windsurf bridge...');
    
    // Gerar bridge TypeScript
    const bridgeContent = `/**
 * Onion Bridge for Windsurf IDE
 * Auto-generated by @onion/cli v4.0.0-beta.1
 * 
 * Descobre recursos do Sistema Onion e gera windsurf.config.yml
 */
import * as fs from 'fs';
import * as path from 'path';
import * as yaml from 'yaml';

interface OnionConfig {
  version: string;
  contexts: string[];
  ides: string[];
}

interface Command {
  name: string;
  path: string;
  context: string;
  level: string;
  relativePath: string;
}

interface Agent {
  name: string;
  path: string;
  context: string;
  relativePath: string;
}

interface OnionResources {
  config: OnionConfig;
  contexts: string[];
  commands: Command[];
  agents: Agent[];
}

export class WindsurfOnionBridge {
  private projectRoot: string;
  private onionRoot: string;
  private config: OnionConfig | null = null;

  constructor(projectRoot: string) {
    this.projectRoot = projectRoot || path.join(__dirname, '../../../');
    this.onionRoot = path.join(this.projectRoot, '.onion');
  }

  /**
   * Carrega configuração .onion-config.yml
   */
  loadConfig(): OnionConfig {
    const configPath = path.join(this.projectRoot, '.onion-config.yml');
    if (!fs.existsSync(configPath)) {
      console.warn('⚠️  .onion-config.yml not found. Using default config.');
      this.config = {
        version: '4.0.0',
        contexts: [],
        ides: []
      };
      return this.config;
    }
    
    const configContent = fs.readFileSync(configPath, 'utf-8');
    this.config = yaml.parse(configContent);
    return this.config;
  }

  /**
   * Descobre contextos disponíveis
   */
  discoverContexts(): string[] {
    const contextsDir = path.join(this.onionRoot, 'contexts');
    if (!fs.existsSync(contextsDir)) {
      return [];
    }
    
    return fs.readdirSync(contextsDir).filter(name => {
      const contextPath = path.join(contextsDir, name);
      return fs.statSync(contextPath).isDirectory();
    });
  }

  /**
   * Descobre comandos por contexto
   */
  discoverCommands(context: string): Command[] {
    const commands: Command[] = [];
    const contextCommandsDir = path.join(this.onionRoot, 'contexts', context, 'commands');
    
    if (!fs.existsSync(contextCommandsDir)) {
      return commands;
    }
    
    // Buscar em todos os níveis
    const levels = ['starter', 'intermediate', 'advanced'];
    levels.forEach(level => {
      const levelDir = path.join(contextCommandsDir, level);
      if (fs.existsSync(levelDir)) {
        const files = fs.readdirSync(levelDir);
        files.forEach(file => {
          if (file.endsWith('.md')) {
            commands.push({
              name: file.replace('.md', ''),
              path: path.join(levelDir, file),
              context,
              level,
              relativePath: path.relative(this.projectRoot, path.join(levelDir, file))
            });
          }
        });
      }
    });
    
    // Comandos na raiz do contexto (ex: help.md)
    const rootFiles = fs.readdirSync(contextCommandsDir);
    rootFiles.forEach(file => {
      const filePath = path.join(contextCommandsDir, file);
      if (fs.statSync(filePath).isFile() && file.endsWith('.md')) {
        commands.push({
          name: file.replace('.md', ''),
          path: filePath,
          context,
          level: 'root',
          relativePath: path.relative(this.projectRoot, filePath)
        });
      }
    });
    
    return commands;
  }

  /**
   * Descobre agentes por contexto
   */
  discoverAgents(context: string): Agent[] {
    const agents: Agent[] = [];
    const contextAgentsDir = path.join(this.onionRoot, 'contexts', context, 'agents');
    
    if (!fs.existsSync(contextAgentsDir)) {
      return agents;
    }
    
    const files = fs.readdirSync(contextAgentsDir);
    files.forEach(file => {
      if (file.endsWith('.md')) {
        agents.push({
          name: file.replace('.md', ''),
          path: path.join(contextAgentsDir, file),
          context,
          relativePath: path.relative(this.projectRoot, path.join(contextAgentsDir, file))
        });
      }
    });
    
    return agents;
  }

  /**
   * Descobre comandos core
   */
  discoverCoreCommands(): Command[] {
    const commands: Command[] = [];
    const coreCommandsDir = path.join(this.onionRoot, 'core', 'commands');
    
    if (!fs.existsSync(coreCommandsDir)) {
      return commands;
    }
    
    const files = fs.readdirSync(coreCommandsDir);
    files.forEach(file => {
      if (file.endsWith('.md')) {
        commands.push({
          name: file.replace('.md', ''),
          path: path.join(coreCommandsDir, file),
          context: 'core',
          level: 'core',
          relativePath: path.relative(this.projectRoot, path.join(coreCommandsDir, file))
        });
      }
    });
    
    return commands;
  }

  /**
   * Descobre agentes core
   */
  discoverCoreAgents(): Agent[] {
    const agents: Agent[] = [];
    const coreAgentsDir = path.join(this.onionRoot, 'core', 'agents');
    
    if (!fs.existsSync(coreAgentsDir)) {
      return agents;
    }
    
    const files = fs.readdirSync(coreAgentsDir);
    files.forEach(file => {
      if (file.endsWith('.md')) {
        agents.push({
          name: file.replace('.md', ''),
          path: path.join(coreAgentsDir, file),
          context: 'core',
          relativePath: path.relative(this.projectRoot, path.join(coreAgentsDir, file))
        });
      }
    });
    
    return agents;
  }

  /**
   * Descobre todos os recursos
   */
  discover(): OnionResources {
    if (!this.config) {
      this.loadConfig();
    }
    
    const contexts = this.discoverContexts();
    const commands: Command[] = [];
    const agents: Agent[] = [];
    
    // Comandos e agentes core
    commands.push(...this.discoverCoreCommands());
    agents.push(...this.discoverCoreAgents());
    
    // Comandos e agentes por contexto
    contexts.forEach(context => {
      commands.push(...this.discoverCommands(context));
      agents.push(...this.discoverAgents(context));
    });
    
    return {
      config: this.config!,
      contexts,
      commands,
      agents
    };
  }

  /**
   * Gera windsurf.config.yml
   */
  async generateConfig(): Promise<void> {
    const resources = this.discover();
    const configPath = path.join(this.projectRoot, 'windsurf.config.yml');
    
    // Mapear comandos para formato Windsurf
    const windsurfCommands = resources.commands.map(cmd => ({
      name: cmd.context === 'core' ? cmd.name : \`\${cmd.context}/\${cmd.name}\`,
      path: cmd.relativePath,
      context: cmd.context,
      level: cmd.level,
      description: \`Onion command: \${cmd.context}/\${cmd.name} (\${cmd.level})\`
    }));
    
    // Mapear agentes para formato Windsurf
    const windsurfAgents = resources.agents.map(agent => ({
      name: agent.context === 'core' ? agent.name : \`\${agent.context}/\${agent.name}\`,
      path: agent.relativePath,
      context: agent.context,
      description: \`Onion agent: \${agent.context}/\${agent.name}\`
    }));
    
    // Gerar config YAML
    const windsurfConfig = {
      onion: {
        version: '4.0.0-beta.1',
        generated: new Date().toISOString(),
        contexts: resources.contexts,
        commands: windsurfCommands,
        agents: windsurfAgents
      },
      // Estrutura para Windsurf IDE
      commands: windsurfCommands.map(cmd => ({
        name: cmd.name,
        path: cmd.path,
        metadata: {
          context: cmd.context,
          level: cmd.level,
          description: cmd.description
        }
      })),
      agents: windsurfAgents.map(agent => ({
        name: agent.name,
        path: agent.path,
        metadata: {
          context: agent.context,
          description: agent.description
        }
      }))
    };
    
    const yamlContent = yaml.stringify(windsurfConfig, {
      indent: 2,
      lineWidth: 0
    });
    
    fs.writeFileSync(configPath, yamlContent, 'utf-8');
    console.log(\`✅ Generated windsurf.config.yml with \${resources.commands.length} commands and \${resources.agents.length} agents\`);
  }
}

// Singleton instance
let bridgeInstance: WindsurfOnionBridge | null = null;

export function getBridge(projectRoot?: string): WindsurfOnionBridge {
  if (!bridgeInstance) {
    bridgeInstance = new WindsurfOnionBridge(projectRoot || process.cwd());
  }
  return bridgeInstance;
}

// Auto-executar se chamado diretamente
if (require.main === module) {
  const bridge = getBridge();
  bridge.generateConfig().catch(err => {
    console.error('❌ Error generating Windsurf config:', err);
    process.exit(1);
  });
}
`;

    await fs.writeFile(
      path.join(loaderPath, 'onion-bridge.ts'),
      bridgeContent,
      'utf-8'
    );

    // Gerar windsurf.config.yml inicial
    await this.generateWindsurfConfig(loaderPath);

    // Criar README.md para Windsurf
    const readmeContent = `# Windsurf IDE Integration

Este diretório contém o bridge TypeScript que conecta o Sistema Onion ao Windsurf IDE.

## Arquivos

- \`onion-bridge.ts\` - Bridge TypeScript que descobre recursos Onion
- \`windsurf.config.yml\` - Configuração gerada automaticamente (na raiz do projeto)

## Como Funciona

1. O bridge descobre todos os recursos Onion (comandos, agentes, contextos)
2. Gera \`windsurf.config.yml\` na raiz do projeto
3. Windsurf lê o config e disponibiliza comandos/agentes

## Uso

### Gerar Config Manualmente

\`\`\`bash
# Compilar TypeScript (se necessário)
npx ts-node .onion/ide/windsurf/onion-bridge.ts

# Ou usar via Node.js diretamente
node -r ts-node/register .onion/ide/windsurf/onion-bridge.ts
\`\`\`

### Auto-geração

O config é gerado automaticamente quando você executa:
- \`onion init\` - Inicialização do projeto
- \`onion add windsurf\` - Adicionar suporte Windsurf

## Estrutura do Config

\`\`\`yaml
onion:
  version: 4.0.0-beta.1
  contexts: [business, technical]
  commands: [...]
  agents: [...]

commands:
  - name: business/spec
    path: .onion/contexts/business/commands/starter/spec.md
    metadata:
      context: business
      level: starter

agents:
  - name: business/product-agent
    path: .onion/contexts/business/agents/product-agent.md
    metadata:
      context: business
\`\`\`

## Troubleshooting

### Config não é gerado

Verifique se \`.onion-config.yml\` existe na raiz do projeto.

### Comandos não aparecem no Windsurf

1. Verifique se \`windsurf.config.yml\` existe na raiz
2. Reinicie o Windsurf IDE
3. Verifique logs do Windsurf para erros

## Documentação

Para mais informações, consulte:
- [Arquitetura IDE Loaders](../../../docs/onion/ide-loaders-architecture.md)
- [Sistema Onion v4](../../../docs/onion/README.md)
`;

    await fs.writeFile(
      path.join(loaderPath, 'README.md'),
      readmeContent,
      'utf-8'
    );

    logger.stopSpinner(true, 'Generated Windsurf bridge');
  }

  /**
   * Gera windsurf.config.yml na raiz do projeto
   */
  async generateWindsurfConfig(loaderPath) {
    // Simular descoberta para gerar config inicial
    const projectRoot = path.resolve(loaderPath, '../../../');
    const onionRoot = path.join(projectRoot, '.onion');
    
    if (!fs.existsSync(onionRoot)) {
      logger.warn('⚠️  .onion/ not found. Skipping windsurf.config.yml generation.');
      return;
    }

    // Usar lógica similar ao Cursor loader para descobrir recursos
    const contextsDir = path.join(onionRoot, 'contexts');
    const contexts = fs.existsSync(contextsDir)
      ? fs.readdirSync(contextsDir).filter(name => {
          const contextPath = path.join(contextsDir, name);
          return fs.statSync(contextPath).isDirectory();
        })
      : [];

    const commands = [];
    const agents = [];

    // Descobrir comandos e agentes core
    const coreCommandsDir = path.join(onionRoot, 'core', 'commands');
    const coreAgentsDir = path.join(onionRoot, 'core', 'agents');

    if (fs.existsSync(coreCommandsDir)) {
      fs.readdirSync(coreCommandsDir).forEach(file => {
        if (file.endsWith('.md')) {
          commands.push({
            name: file.replace('.md', ''),
            path: path.relative(projectRoot, path.join(coreCommandsDir, file)),
            context: 'core',
            level: 'core'
          });
        }
      });
    }

    if (fs.existsSync(coreAgentsDir)) {
      fs.readdirSync(coreAgentsDir).forEach(file => {
        if (file.endsWith('.md')) {
          agents.push({
            name: file.replace('.md', ''),
            path: path.relative(projectRoot, path.join(coreAgentsDir, file)),
            context: 'core'
          });
        }
      });
    }

    // Descobrir por contexto
    contexts.forEach(context => {
      const contextCommandsDir = path.join(onionRoot, 'contexts', context, 'commands');
      const contextAgentsDir = path.join(onionRoot, 'contexts', context, 'agents');

      ['starter', 'intermediate', 'advanced'].forEach(level => {
        const levelDir = path.join(contextCommandsDir, level);
        if (fs.existsSync(levelDir)) {
          fs.readdirSync(levelDir).forEach(file => {
            if (file.endsWith('.md')) {
              commands.push({
                name: file.replace('.md', ''),
                path: path.relative(projectRoot, path.join(levelDir, file)),
                context,
                level
              });
            }
          });
        }
      });

      // Comandos na raiz do contexto
      if (fs.existsSync(contextCommandsDir)) {
        fs.readdirSync(contextCommandsDir).forEach(file => {
          const filePath = path.join(contextCommandsDir, file);
          if (fs.statSync(filePath).isFile() && file.endsWith('.md')) {
            commands.push({
              name: file.replace('.md', ''),
              path: path.relative(projectRoot, filePath),
              context,
              level: 'root'
            });
          }
        });
      }

      if (fs.existsSync(contextAgentsDir)) {
        fs.readdirSync(contextAgentsDir).forEach(file => {
          if (file.endsWith('.md')) {
            agents.push({
              name: file.replace('.md', ''),
              path: path.relative(projectRoot, path.join(contextAgentsDir, file)),
              context
            });
          }
        });
      }
    });

    // Gerar config YAML
    const yaml = require('yaml');
    const windsurfConfig = {
      onion: {
        version: '4.0.0-beta.1',
        generated: new Date().toISOString(),
        contexts,
        commands: commands.map(cmd => ({
          name: cmd.context === 'core' ? cmd.name : `${cmd.context}/${cmd.name}`,
          path: cmd.path,
          context: cmd.context,
          level: cmd.level
        })),
        agents: agents.map(agent => ({
          name: agent.context === 'core' ? agent.name : `${agent.context}/${agent.name}`,
          path: agent.path,
          context: agent.context
        }))
      },
      commands: commands.map(cmd => ({
        name: cmd.context === 'core' ? cmd.name : `${cmd.context}/${cmd.name}`,
        path: cmd.path,
        metadata: {
          context: cmd.context,
          level: cmd.level
        }
      })),
      agents: agents.map(agent => ({
        name: agent.context === 'core' ? agent.name : `${agent.context}/${agent.name}`,
        path: agent.path,
        metadata: {
          context: agent.context
        }
      }))
    };

    const configPath = path.join(projectRoot, 'windsurf.config.yml');
    const yamlContent = yaml.stringify(windsurfConfig, {
      indent: 2,
      lineWidth: 0
    });

    await fs.writeFile(configPath, yamlContent, 'utf-8');
    logger.info(`✅ Generated windsurf.config.yml with ${commands.length} commands and ${agents.length} agents`);
  }
  
  async generateClaudeLoader(loaderPath) {
    logger.startSpinner('Generating claude adapter...');
    
    // Gerar adapter Python
    const adapterContent = `#!/usr/bin/env python3
"""
Onion Adapter for Claude Code IDE
Auto-generated by @onion/cli v4.0.0-beta.1

Descobre recursos do Sistema Onion e gera claude.config.json
"""
import json
import os
from pathlib import Path
from typing import Dict, List, Optional
from datetime import datetime

try:
    import yaml
except ImportError:
    print("⚠️  Warning: PyYAML not installed. Install with: pip install pyyaml")
    yaml = None


class ClaudeOnionAdapter:
    """Adapter para descobrir e mapear recursos Onion para Claude Code"""
    
    def __init__(self, project_root: Optional[str] = None):
        """
        Inicializa o adapter
        
        Args:
            project_root: Raiz do projeto (padrão: diretório atual)
        """
        if project_root is None:
            # Tentar encontrar raiz do projeto (subir até encontrar .onion/)
            current = Path.cwd()
            while current != current.parent:
                if (current / '.onion').exists():
                    project_root = str(current)
                    break
                current = current.parent
            else:
                project_root = str(Path.cwd())
        
        self.project_root = Path(project_root)
        self.onion_root = self.project_root / '.onion'
        self.config: Optional[Dict] = None
    
    def load_config(self) -> Dict:
        """
        Carrega configuração .onion-config.yml
        
        Returns:
            Dicionário com configuração Onion
        """
        config_path = self.project_root / '.onion-config.yml'
        
        if not config_path.exists():
            print("⚠️  .onion-config.yml not found. Using default config.")
            self.config = {
                'version': '4.0.0',
                'contexts': [],
                'ides': []
            }
            return self.config
        
        if yaml is None:
            # Fallback: ler como texto e fazer parse básico
            print("⚠️  PyYAML not available. Using basic config.")
            self.config = {
                'version': '4.0.0',
                'contexts': [],
                'ides': []
            }
            return self.config
        
        with open(config_path, 'r', encoding='utf-8') as f:
            self.config = yaml.safe_load(f) or {}
        
        return self.config
    
    def discover_contexts(self) -> List[str]:
        """
        Descobre contextos disponíveis
        
        Returns:
            Lista de nomes de contextos
        """
        contexts_dir = self.onion_root / 'contexts'
        
        if not contexts_dir.exists():
            return []
        
        contexts = []
        for item in contexts_dir.iterdir():
            if item.is_dir():
                contexts.append(item.name)
        
        return sorted(contexts)
    
    def discover_commands(self, context: str) -> List[Dict]:
        """
        Descobre comandos por contexto
        
        Args:
            context: Nome do contexto
            
        Returns:
            Lista de dicionários com informações dos comandos
        """
        commands = []
        context_commands_dir = self.onion_root / 'contexts' / context / 'commands'
        
        if not context_commands_dir.exists():
            return commands
        
        # Buscar em todos os níveis
        levels = ['starter', 'intermediate', 'advanced']
        for level in levels:
            level_dir = context_commands_dir / level
            if level_dir.exists():
                for file in level_dir.iterdir():
                    if file.is_file() and file.suffix == '.md':
                        commands.append({
                            'name': file.stem,
                            'path': str(file.relative_to(self.project_root)),
                            'context': context,
                            'level': level,
                            'relative_path': str(file.relative_to(self.project_root))
                        })
        
        # Comandos na raiz do contexto (ex: help.md)
        for file in context_commands_dir.iterdir():
            if file.is_file() and file.suffix == '.md':
                # Evitar duplicatas (já adicionados dos níveis)
                if not any(cmd['name'] == file.stem and cmd['context'] == context 
                          for cmd in commands):
                    commands.append({
                        'name': file.stem,
                        'path': str(file.relative_to(self.project_root)),
                        'context': context,
                        'level': 'root',
                        'relative_path': str(file.relative_to(self.project_root))
                    })
        
        return commands
    
    def discover_agents(self, context: str) -> List[Dict]:
        """
        Descobre agentes por contexto
        
        Args:
            context: Nome do contexto
            
        Returns:
            Lista de dicionários com informações dos agentes
        """
        agents = []
        context_agents_dir = self.onion_root / 'contexts' / context / 'agents'
        
        if not context_agents_dir.exists():
            return agents
        
        for file in context_agents_dir.iterdir():
            if file.is_file() and file.suffix == '.md':
                agents.append({
                    'name': file.stem,
                    'path': str(file.relative_to(self.project_root)),
                    'context': context,
                    'relative_path': str(file.relative_to(self.project_root))
                })
        
        return agents
    
    def discover_core_commands(self) -> List[Dict]:
        """
        Descobre comandos core
        
        Returns:
            Lista de comandos core
        """
        commands = []
        core_commands_dir = self.onion_root / 'core' / 'commands'
        
        if not core_commands_dir.exists():
            return commands
        
        for file in core_commands_dir.iterdir():
            if file.is_file() and file.suffix == '.md':
                commands.append({
                    'name': file.stem,
                    'path': str(file.relative_to(self.project_root)),
                    'context': 'core',
                    'level': 'core',
                    'relative_path': str(file.relative_to(self.project_root))
                })
        
        return commands
    
    def discover_core_agents(self) -> List[Dict]:
        """
        Descobre agentes core
        
        Returns:
            Lista de agentes core
        """
        agents = []
        core_agents_dir = self.onion_root / 'core' / 'agents'
        
        if not core_agents_dir.exists():
            return agents
        
        for file in core_agents_dir.iterdir():
            if file.is_file() and file.suffix == '.md':
                agents.append({
                    'name': file.stem,
                    'path': str(file.relative_to(self.project_root)),
                    'context': 'core',
                    'relative_path': str(file.relative_to(self.project_root))
                })
        
        return agents
    
    def discover(self) -> Dict:
        """
        Descobre todos os recursos Onion
        
        Returns:
            Dicionário com todos os recursos descobertos
        """
        if self.config is None:
            self.load_config()
        
        contexts = self.discover_contexts()
        commands = []
        agents = []
        
        # Comandos e agentes core
        commands.extend(self.discover_core_commands())
        agents.extend(self.discover_core_agents())
        
        # Comandos e agentes por contexto
        for context in contexts:
            commands.extend(self.discover_commands(context))
            agents.extend(self.discover_agents(context))
        
        return {
            'config': self.config or {},
            'contexts': contexts,
            'commands': commands,
            'agents': agents
        }
    
    def generate_config(self) -> None:
        """
        Gera claude.config.json na raiz do projeto
        """
        resources = self.discover()
        config_path = self.project_root / 'claude.config.json'
        
        # Mapear comandos para formato Claude
        claude_commands = []
        for cmd in resources['commands']:
            command_name = cmd['name'] if cmd['context'] == 'core' else f"{cmd['context']}/{cmd['name']}"
            claude_commands.append({
                'name': command_name,
                'path': cmd['relative_path'],
                'context': cmd['context'],
                'level': cmd['level'],
                'description': f"Onion command: {command_name} ({cmd['level']})"
            })
        
        # Mapear agentes para formato Claude
        claude_agents = []
        for agent in resources['agents']:
            agent_name = agent['name'] if agent['context'] == 'core' else f"{agent['context']}/{agent['name']}"
            claude_agents.append({
                'name': agent_name,
                'path': agent['relative_path'],
                'context': agent['context'],
                'description': f"Onion agent: {agent_name}"
            })
        
        # Gerar config JSON
        claude_config = {
            'onion': {
                'version': '4.0.0-beta.1',
                'generated': datetime.now().isoformat(),
                'contexts': resources['contexts'],
                'commands': claude_commands,
                'agents': claude_agents
            },
            'commands': [
                {
                    'name': cmd['name'],
                    'path': cmd['path'],
                    'metadata': {
                        'context': cmd['context'],
                        'level': cmd['level'],
                        'description': cmd['description']
                    }
                }
                for cmd in claude_commands
            ],
            'agents': [
                {
                    'name': agent['name'],
                    'path': agent['path'],
                    'metadata': {
                        'context': agent['context'],
                        'description': agent['description']
                    }
                }
                for agent in claude_agents
            ]
        }
        
        with open(config_path, 'w', encoding='utf-8') as f:
            json.dump(claude_config, f, indent=2, ensure_ascii=False)
        
        print("✅ Generated claude.config.json with " + str(len(claude_commands)) + " commands and " + str(len(claude_agents)) + " agents")
    
    def generate_claude_md(self) -> None:
        """
        Gera CLAUDE.md com instruções para Claude Code
        """
        resources = self.discover()
        claude_md_path = self.project_root / 'CLAUDE.md'
        
        # Construir conteúdo Markdown
        md_lines = [
            "# Sistema Onion - Claude Code Integration",
            "",
            "Este projeto usa o **Sistema Onion v4.0** - Multi-Context Development Orchestrator.",
            "",
            "## Contextos Disponíveis",
            ""
        ]
        
        # Adicionar contextos
        for ctx in resources['contexts']:
            help_str = "help"
            backtick = chr(96)
            context_line = "- **" + ctx + "**: Use " + backtick + "/" + ctx + "/" + help_str + backtick + " para ver comandos disponíveis"
            md_lines.append(context_line)
        
        md_lines.extend([
            "",
            "## Comandos Principais",
            "",
            "### Core Commands"
        ])
        
        # Adicionar comandos core
        core_commands = [cmd for cmd in resources['commands'] if cmd['context'] == 'core' and cmd['level'] == 'core']
        for cmd in core_commands:
            desc = cmd.get('description', 'Onion command')
            cmd_name = cmd['name']
            backtick = chr(96)
            cmd_line = "- " + backtick + "/" + cmd_name + backtick + " - " + desc
            md_lines.append(cmd_line)
        
        md_lines.append("")
        md_lines.append("### Por Contexto")
        md_lines.append("")
        
        # Adicionar comandos por contexto
        for ctx in resources['contexts']:
            md_lines.append("### " + ctx.capitalize())
            starter_commands = [cmd for cmd in resources['commands'] if cmd['context'] == ctx and cmd['level'] == 'starter']
            backtick = chr(96)
            for cmd in starter_commands[:5]:  # Limitar a 5 por contexto
                cmd_name = cmd['name']
                cmd_level = cmd.get('level', 'command')
                cmd_line = "- " + backtick + "/" + ctx + "/" + cmd_name + backtick + " - " + cmd_level
                md_lines.append(cmd_line)
            md_lines.append("")
        
        md_lines.extend([
            "## Agentes Disponíveis",
            ""
        ])
        
        # Adicionar agentes (limitar a 10)
        for agent in resources['agents'][:10]:
            agent_name = agent['name']
            agent_context = agent['context']
            # Construir linha usando partes separadas para evitar problemas com @ e backticks
            prefix_part = "- "
            backtick_start = chr(96)
            at_symbol = chr(64)
            backtick_end = chr(96)
            suffix_part = " - Agente do contexto "
            agent_line = prefix_part + backtick_start + at_symbol + agent_name + backtick_end + suffix_part + agent_context
            md_lines.append(agent_line)
        
        md_lines.extend([
            "",
            "## Como Usar",
            "",
            "1. Use comandos com / seguido do contexto e nome: /contexto/comando",
            "2. Use agentes com " + chr(64) + " seguido do nome: " + chr(64) + "product-agent",
            "3. Consulte /help para ajuda global ou /contexto/help para contexto especifico",
            "",
            "## Configuração",
            "",
            "- **Config**: " + chr(96) + "claude.config.json" + chr(96) + " (gerado automaticamente)",
            "- **Onion Root**: " + chr(96) + ".onion/" + chr(96),
            "- **Versão**: 4.0.0-beta.1",
            "",
            "---",
            "",
            "**Gerado por**: " + chr(64) + "onion/cli v4.0.0-beta.1",
            "**Última atualização**: " + datetime.now().isoformat()
        ])
        
        md_content = "\\n".join(md_lines)
        
        with open(claude_md_path, 'w', encoding='utf-8') as f:
            f.write(md_content)
        
        print("✅ Generated CLAUDE.md")


# Singleton instance
_adapter_instance: Optional[ClaudeOnionAdapter] = None


def get_adapter(project_root: Optional[str] = None) -> ClaudeOnionAdapter:
    """
    Obtém instância singleton do adapter
    
    Args:
        project_root: Raiz do projeto (opcional)
        
    Returns:
        Instância do ClaudeOnionAdapter
    """
    global _adapter_instance
    if _adapter_instance is None:
        _adapter_instance = ClaudeOnionAdapter(project_root)
    return _adapter_instance


# Auto-executar se chamado diretamente
if __name__ == '__main__':
    import sys
    
    project_root = sys.argv[1] if len(sys.argv) > 1 else None
    adapter = get_adapter(project_root)
    
    try:
        adapter.generate_config()
        adapter.generate_claude_md()
        print("✅ Claude adapter executed successfully")
    except Exception as e:
        print(f"❌ Error: {e}", file=sys.stderr)
        import traceback
        traceback.print_exc()
        sys.exit(1)
`;

    await fs.writeFile(
      path.join(loaderPath, 'onion-adapter.py'),
      adapterContent,
      'utf-8'
    );

    // Tornar executável (Unix-like)
    try {
      await fs.chmod(path.join(loaderPath, 'onion-adapter.py'), 0o755);
    } catch (err) {
      // Ignorar erro em Windows
    }

    // Gerar claude.config.json inicial
    await this.generateClaudeConfig(loaderPath);

    // Criar README.md para Claude
    const readmeContent = `# Claude Code IDE Integration

Este diretório contém o adapter Python que conecta o Sistema Onion ao Claude Code IDE.

## Arquivos

- \`onion-adapter.py\` - Adapter Python que descobre recursos Onion
- \`claude.config.json\` - Configuração gerada automaticamente (na raiz do projeto)
- \`CLAUDE.md\` - Instruções para Claude Code (na raiz do projeto)

## Como Funciona

1. O adapter descobre todos os recursos Onion (comandos, agentes, contextos)
2. Gera \`claude.config.json\` na raiz do projeto
3. Gera \`CLAUDE.md\` com instruções para Claude Code
4. Claude Code lê os arquivos e disponibiliza comandos/agentes

## Pré-requisitos

- Python 3.7+
- PyYAML (opcional, mas recomendado): \`pip install pyyaml\`

## Uso

### Gerar Config Manualmente

\`\`\`bash
# Executar adapter diretamente
python3 .onion/ide/claude/onion-adapter.py

# Ou especificar raiz do projeto
python3 .onion/ide/claude/onion-adapter.py /path/to/project
\`\`\`

### Auto-geração

O config é gerado automaticamente quando você executa:
- \`onion init\` - Inicialização do projeto
- \`onion add claude-code\` - Adicionar suporte Claude Code

## Estrutura do Config

\`\`\`json
{
  "onion": {
    "version": "4.0.0-beta.1",
    "contexts": ["business", "technical"],
    "commands": [...],
    "agents": [...]
  },
  "commands": [
    {
      "name": "business/spec",
      "path": ".onion/contexts/business/commands/starter/spec.md",
      "metadata": {
        "context": "business",
        "level": "starter"
      }
    }
  ],
  "agents": [...]
}
\`\`\`

## Integração com MCP (Model Context Protocol)

O adapter pode ser usado com MCP para expor comandos Onion via protocolo MCP.

### Exemplo de Uso MCP

\`\`\`python
from .onion.ide.claude.onion_adapter import get_adapter

adapter = get_adapter()
resources = adapter.discover()

# Expor via MCP
# (implementação específica depende do servidor MCP)
\`\`\`

## Troubleshooting

### Erro: PyYAML not installed

Instale PyYAML:
\`\`\`bash
pip install pyyaml
\`\`\`

O adapter funciona sem PyYAML, mas com funcionalidade limitada.

### Config não é gerado

Verifique se \`.onion-config.yml\` existe na raiz do projeto.

### Comandos não aparecem no Claude Code

1. Verifique se \`claude.config.json\` existe na raiz
2. Verifique se \`CLAUDE.md\` existe na raiz
3. Reinicie o Claude Code
4. Verifique logs do Claude Code para erros

## Documentação

Para mais informações, consulte:
- [Arquitetura IDE Loaders](../../../docs/onion/ide-loaders-architecture.md)
- [Sistema Onion v4](../../../docs/onion/README.md)
- [Claude Code Documentation](https://claude.ai/docs)
`;

    await fs.writeFile(
      path.join(loaderPath, 'README.md'),
      readmeContent,
      'utf-8'
    );

    logger.stopSpinner(true, 'Generated Claude adapter');
  }

  /**
   * Gera claude.config.json na raiz do projeto
   */
  async generateClaudeConfig(loaderPath) {
    const projectRoot = path.resolve(loaderPath, '../../../');
    const onionRoot = path.join(projectRoot, '.onion');
    
    if (!fs.existsSync(onionRoot)) {
      logger.warn('⚠️  .onion/ not found. Skipping claude.config.json generation.');
      return;
    }

    // Usar lógica similar aos outros loaders para descobrir recursos
    const contextsDir = path.join(onionRoot, 'contexts');
    const contexts = fs.existsSync(contextsDir)
      ? fs.readdirSync(contextsDir).filter(name => {
          const contextPath = path.join(contextsDir, name);
          return fs.statSync(contextPath).isDirectory();
        })
      : [];

    const commands = [];
    const agents = [];

    // Descobrir comandos e agentes core
    const coreCommandsDir = path.join(onionRoot, 'core', 'commands');
    const coreAgentsDir = path.join(onionRoot, 'core', 'agents');

    if (fs.existsSync(coreCommandsDir)) {
      fs.readdirSync(coreCommandsDir).forEach(file => {
        if (file.endsWith('.md')) {
          commands.push({
            name: file.replace('.md', ''),
            path: path.relative(projectRoot, path.join(coreCommandsDir, file)),
            context: 'core',
            level: 'core'
          });
        }
      });
    }

    if (fs.existsSync(coreAgentsDir)) {
      fs.readdirSync(coreAgentsDir).forEach(file => {
        if (file.endsWith('.md')) {
          agents.push({
            name: file.replace('.md', ''),
            path: path.relative(projectRoot, path.join(coreAgentsDir, file)),
            context: 'core'
          });
        }
      });
    }

    // Descobrir por contexto
    contexts.forEach(context => {
      const contextCommandsDir = path.join(onionRoot, 'contexts', context, 'commands');
      const contextAgentsDir = path.join(onionRoot, 'contexts', context, 'agents');

      ['starter', 'intermediate', 'advanced'].forEach(level => {
        const levelDir = path.join(contextCommandsDir, level);
        if (fs.existsSync(levelDir)) {
          fs.readdirSync(levelDir).forEach(file => {
            if (file.endsWith('.md')) {
              commands.push({
                name: file.replace('.md', ''),
                path: path.relative(projectRoot, path.join(levelDir, file)),
                context,
                level
              });
            }
          });
        }
      });

      // Comandos na raiz do contexto
      if (fs.existsSync(contextCommandsDir)) {
        fs.readdirSync(contextCommandsDir).forEach(file => {
          const filePath = path.join(contextCommandsDir, file);
          if (fs.statSync(filePath).isFile() && file.endsWith('.md')) {
            // Evitar duplicatas
            if (!commands.some(cmd => cmd.name === file.replace('.md', '') && cmd.context === context)) {
              commands.push({
                name: file.replace('.md', ''),
                path: path.relative(projectRoot, filePath),
                context,
                level: 'root'
              });
            }
          }
        });
      }

      if (fs.existsSync(contextAgentsDir)) {
        fs.readdirSync(contextAgentsDir).forEach(file => {
          if (file.endsWith('.md')) {
            agents.push({
              name: file.replace('.md', ''),
              path: path.relative(projectRoot, path.join(contextAgentsDir, file)),
              context
            });
          }
        });
      }
    });

    // Gerar config JSON
    const claudeCommands = commands.map(cmd => ({
      name: cmd.context === 'core' ? cmd.name : `${cmd.context}/${cmd.name}`,
      path: cmd.path,
      context: cmd.context,
      level: cmd.level,
      description: `Onion command: ${cmd.context}/${cmd.name} (${cmd.level})`
    }));

    const claudeAgents = agents.map(agent => ({
      name: agent.context === 'core' ? agent.name : `${agent.context}/${agent.name}`,
      path: agent.path,
      context: agent.context,
      description: `Onion agent: ${agent.context}/${agent.name}`
    }));

    const claudeConfig = {
      onion: {
        version: '4.0.0-beta.1',
        generated: new Date().toISOString(),
        contexts,
        commands: claudeCommands,
        agents: claudeAgents
      },
      commands: claudeCommands.map(cmd => ({
        name: cmd.name,
        path: cmd.path,
        metadata: {
          context: cmd.context,
          level: cmd.level,
          description: cmd.description
        }
      })),
      agents: claudeAgents.map(agent => ({
        name: agent.name,
        path: agent.path,
        metadata: {
          context: agent.context,
          description: agent.description
        }
      }))
    };

    const configPath = path.join(projectRoot, 'claude.config.json');
    await fs.writeJson(configPath, claudeConfig, { spaces: 2 });
    logger.info(`✅ Generated claude.config.json with ${commands.length} commands and ${agents.length} agents`);
  }
  
  async generateUniversalAgentsMd() {
    logger.startSpinner('Generating universal AGENTS.md...');
    
    const agentsMdContent = `# Sistema Onion - Universal Agents

Este arquivo serve como fallback para IDEs que não possuem suporte nativo ao Sistema Onion.

## Comandos Disponíveis

### Core Commands
- \`/onion\` - Orquestrador principal
- \`/warm-up\` - Preparar contexto

${this.config.contexts.map(ctx => `
### ${ctx.charAt(0).toUpperCase() + ctx.slice(1)} Context
- \`/${ctx}/spec\` - Criar especificação
- \`/${ctx}/help\` - Ajuda do contexto
`).join('')}

## Como Usar

Mencione os comandos acima no chat do seu IDE.

## Configuração

Este projeto usa Sistema Onion v3.0. Para melhor experiência, use:
- Cursor IDE
- Windsurf
- Claude Code

Ou acesse a documentação em \`.onion/README.md\`
`;
    
    const universalPath = path.join(
      this.projectRoot,
      '.onion',
      'ide',
      'universal'
    );
    
    await fs.writeFile(
      path.join(universalPath, 'AGENTS.md'),
      agentsMdContent,
      'utf-8'
    );
    
    logger.stopSpinner(true, 'Created universal AGENTS.md');
  }
  
  // Criar estrutura na raiz do projeto para o IDE reconhecer
  async createIDERootStructure(ide) {
    if (ide === 'cursor') {
      await this.createCursorRootStructure();
    } else if (ide === 'windsurf') {
      await this.createWindsurfRootStructure();
    } else if (ide === 'claude-code') {
      await this.createClaudeRootStructure();
    }
  }
  
  async createCursorRootStructure() {
    logger.startSpinner('Creating .cursor/ structure...');
    
    const cursorRoot = path.join(this.projectRoot, '.cursor');
    await fs.ensureDir(cursorRoot);
    
    // Copiar comandos dos contextos para .cursor/commands/
    const commandsPath = path.join(cursorRoot, 'commands');
    await fs.ensureDir(commandsPath);
    
    // APENAS os contextos selecionados pelo usuário
    for (const context of this.config.contexts) {
      const contextCommandsPath = path.join(commandsPath, context);
      await fs.ensureDir(contextCommandsPath);
      
      // Criar múltiplos comandos starter
      await this.createStarterCommands(context, contextCommandsPath);
    }
    
    // Copiar agentes
    const agentsPath = path.join(cursorRoot, 'agents');
    await fs.ensureDir(agentsPath);
    
    // Copiar agente onion principal
    const onionAgentPath = path.join(
      this.projectRoot,
      '.onion',
      'core',
      'agents',
      'onion.md'
    );
    
    if (await fs.pathExists(onionAgentPath)) {
      await fs.copy(
        onionAgentPath,
        path.join(agentsPath, 'onion.md')
      );
    }
    
    // Criar .cursorrules com instruções
    const cursorRulesContent = `# Sistema Onion v3.0

Este projeto usa o Sistema Onion - Multi-Context Development Orchestrator.

## Estrutura

- **Comandos**: .cursor/commands/
- **Agentes**: .cursor/agents/
- **Fonte**: .onion/

## Contextos Disponíveis

${this.config.contexts.map(ctx => `- **${ctx}**: /${ctx}/*`).join('\n')}

## Comandos Principais

${this.config.contexts.map(ctx => `
### ${ctx.charAt(0).toUpperCase() + ctx.slice(1)}
- \`/${ctx}/help\` - Ver comandos disponíveis
`).join('')}

## Documentação

Consulte \`.onion/README.md\` para mais informações.

---

**Gerado por**: @onion/cli v1.0.0
`;
    
    await fs.writeFile(
      path.join(cursorRoot, '.cursorrules'),
      cursorRulesContent,
      'utf-8'
    );
    
    logger.stopSpinner(true, 'Created .cursor/ structure');
  }
  
  async createStarterCommands(context, commandsPath) {
    // Comandos específicos por contexto
    const starterCommands = {
      business: [
        {
          name: 'help',
          description: `Ajuda do contexto ${context}`,
          content: this.getHelpCommand(context)
        },
        {
          name: 'spec',
          description: 'Criar especificação de feature',
          content: this.getSpecCommand(context)
        },
        {
          name: 'task',
          description: 'Criar task no task manager',
          content: this.getTaskCommand(context)
        }
      ],
      technical: [
        {
          name: 'help',
          description: `Ajuda do contexto ${context}`,
          content: this.getHelpCommand(context)
        },
        {
          name: 'plan',
          description: 'Planejar implementação',
          content: this.getPlanCommand(context)
        },
        {
          name: 'work',
          description: 'Iniciar desenvolvimento',
          content: this.getWorkCommand(context)
        }
      ],
      'customer-success': [
        {
          name: 'help',
          description: `Ajuda do contexto ${context}`,
          content: this.getHelpCommand(context)
        },
        {
          name: 'guide',
          description: 'Criar guia para cliente',
          content: this.getGuideCommand(context)
        }
      ]
    };
    
    // Pegar comandos ou usar default (help apenas)
    const commands = starterCommands[context] || [
      {
        name: 'help',
        description: `Ajuda do contexto ${context}`,
        content: this.getHelpCommand(context)
      }
    ];
    
    // Criar cada comando
    for (const cmd of commands) {
      await fs.writeFile(
        path.join(commandsPath, `${cmd.name}.md`),
        cmd.content,
        'utf-8'
      );
    }
  }
  
  getHelpCommand(context) {
    return `---
name: help
description: Ajuda do contexto ${context}
category: ${context}
version: "3.0.0"
---

# 📚 ${context.charAt(0).toUpperCase() + context.slice(1)} Context - Help

Comandos disponíveis neste contexto.

## 🟢 Starter Commands (essenciais)

- \`/${context}/help\` - Esta ajuda

## 📖 Documentação

Veja documentação completa em \`docs/${context}-context/\`

---

**Fonte**: .onion/contexts/${context}/commands/starter/help.md  
**Auto-gerado por**: @onion/cli
`;
  }
  
  getSpecCommand(context) {
    return `---
name: spec
description: Criar especificação de feature
category: ${context}
version: "3.0.0"
parameters:
  - name: feature
    description: Nome da feature
    required: true
---

# 📋 Criar Especificação

Cria especificação estruturada de uma feature.

## Uso

\`\`\`bash
/${context}/spec "nome-da-feature"
\`\`\`

## O Que Faz

1. Coleta requisitos da feature
2. Estrutura em formato padronizado
3. Salva em \`docs/${context}-context/features/\`
4. Cria task no task manager (se configurado)

## Próximo Passo

Após criar spec, use \`/technical/plan "nome-da-feature"\` para planejar implementação.

---

**Auto-gerado por**: @onion/cli
`;
  }
  
  getPlanCommand(context) {
    return `---
name: plan
description: Planejar implementação técnica
category: ${context}
version: "3.0.0"
parameters:
  - name: feature
    description: Nome da feature
    required: true
---

# 🔧 Planejar Implementação

Cria plano técnico de implementação.

## Uso

\`\`\`bash
/${context}/plan "nome-da-feature"
\`\`\`

## O Que Faz

1. Analisa spec da feature
2. Cria arquitetura técnica
3. Define fases de implementação
4. Salva em \`.onion/contexts/technical/sessions/\`

## Próximo Passo

Use \`/technical/work "nome-da-feature"\` para iniciar desenvolvimento.

---

**Auto-gerado por**: @onion/cli
`;
  }
  
  getTaskCommand(context) {
    return `---
name: task
description: Criar task no task manager
category: ${context}
version: "3.0.0"
parameters:
  - name: title
    description: Título da task
    required: true
---

# ✅ Criar Task

Cria task no task manager configurado.

## Uso

\`\`\`bash
/${context}/task "título da task"
\`\`\`

## Pré-requisitos

Task manager configurado em \`.onion-config.yml\`

---

**Auto-gerado por**: @onion/cli
`;
  }
  
  getWorkCommand(context) {
    return `---
name: work
description: Iniciar desenvolvimento
category: ${context}
version: "3.0.0"
parameters:
  - name: feature
    description: Nome da feature
    required: true
---

# 💻 Iniciar Desenvolvimento

Inicia sessão de desenvolvimento da feature.

## Uso

\`\`\`bash
/${context}/work "nome-da-feature"
\`\`\`

## O Que Faz

1. Carrega plano técnico
2. Cria session em \`.onion/contexts/technical/sessions/\`
3. Prepara contexto para desenvolvimento

---

**Auto-gerado por**: @onion/cli
`;
  }
  
  getGuideCommand(context) {
    return `---
name: guide
description: Criar guia para cliente
category: ${context}
version: "3.0.0"
parameters:
  - name: topic
    description: Tópico do guia
    required: true
---

# 📖 Criar Guia

Cria guia de documentação para cliente.

## Uso

\`\`\`bash
/${context}/guide "tópico"
\`\`\`

## O Que Faz

1. Cria estrutura de guia
2. Salva em \`docs/customer-success-context/guides/\`

---

**Auto-gerado por**: @onion/cli
`;
  }
  
  async createWindsurfRootStructure() {
    // TODO: Implementar .windsurf/
    logger.info('Windsurf root structure - TODO');
  }
  
  async createClaudeRootStructure() {
    // TODO: Implementar .claude/
    logger.info('Claude root structure - TODO');
  }
}

module.exports = LoadersGenerator;

