/**
 * Onion Bridge for Windsurf IDE
 * Auto-generated by @onion/cli v4.0.0-beta.1
 * 
 * Descobre recursos do Sistema Onion e gera windsurf.config.yml
 */
import * as fs from 'fs';
import * as path from 'path';
import * as yaml from 'yaml';

interface OnionConfig {
  version: string;
  contexts: string[];
  ides: string[];
}

interface Command {
  name: string;
  path: string;
  context: string;
  level: string;
  relativePath: string;
}

interface Agent {
  name: string;
  path: string;
  context: string;
  relativePath: string;
}

interface OnionResources {
  config: OnionConfig;
  contexts: string[];
  commands: Command[];
  agents: Agent[];
}

export class WindsurfOnionBridge {
  private projectRoot: string;
  private onionRoot: string;
  private config: OnionConfig | null = null;

  constructor(projectRoot: string) {
    this.projectRoot = projectRoot || path.join(__dirname, '../../../');
    this.onionRoot = path.join(this.projectRoot, '.onion');
  }

  /**
   * Carrega configuração .onion-config.yml
   */
  loadConfig(): OnionConfig {
    const configPath = path.join(this.projectRoot, '.onion-config.yml');
    if (!fs.existsSync(configPath)) {
      console.warn('⚠️  .onion-config.yml not found. Using default config.');
      this.config = {
        version: '4.0.0',
        contexts: [],
        ides: []
      };
      return this.config;
    }
    
    const configContent = fs.readFileSync(configPath, 'utf-8');
    this.config = yaml.parse(configContent);
    return this.config;
  }

  /**
   * Descobre contextos disponíveis
   */
  discoverContexts(): string[] {
    const contextsDir = path.join(this.onionRoot, 'contexts');
    if (!fs.existsSync(contextsDir)) {
      return [];
    }
    
    return fs.readdirSync(contextsDir).filter(name => {
      const contextPath = path.join(contextsDir, name);
      return fs.statSync(contextPath).isDirectory();
    });
  }

  /**
   * Descobre comandos por contexto
   */
  discoverCommands(context: string): Command[] {
    const commands: Command[] = [];
    const contextCommandsDir = path.join(this.onionRoot, 'contexts', context, 'commands');
    
    if (!fs.existsSync(contextCommandsDir)) {
      return commands;
    }
    
    // Buscar em todos os níveis
    const levels = ['starter', 'intermediate', 'advanced'];
    levels.forEach(level => {
      const levelDir = path.join(contextCommandsDir, level);
      if (fs.existsSync(levelDir)) {
        const files = fs.readdirSync(levelDir);
        files.forEach(file => {
          if (file.endsWith('.md')) {
            commands.push({
              name: file.replace('.md', ''),
              path: path.join(levelDir, file),
              context,
              level,
              relativePath: path.relative(this.projectRoot, path.join(levelDir, file))
            });
          }
        });
      }
    });
    
    // Comandos na raiz do contexto (ex: help.md)
    const rootFiles = fs.readdirSync(contextCommandsDir);
    rootFiles.forEach(file => {
      const filePath = path.join(contextCommandsDir, file);
      if (fs.statSync(filePath).isFile() && file.endsWith('.md')) {
        commands.push({
          name: file.replace('.md', ''),
          path: filePath,
          context,
          level: 'root',
          relativePath: path.relative(this.projectRoot, filePath)
        });
      }
    });
    
    return commands;
  }

  /**
   * Descobre agentes por contexto
   */
  discoverAgents(context: string): Agent[] {
    const agents: Agent[] = [];
    const contextAgentsDir = path.join(this.onionRoot, 'contexts', context, 'agents');
    
    if (!fs.existsSync(contextAgentsDir)) {
      return agents;
    }
    
    const files = fs.readdirSync(contextAgentsDir);
    files.forEach(file => {
      if (file.endsWith('.md')) {
        agents.push({
          name: file.replace('.md', ''),
          path: path.join(contextAgentsDir, file),
          context,
          relativePath: path.relative(this.projectRoot, path.join(contextAgentsDir, file))
        });
      }
    });
    
    return agents;
  }

  /**
   * Descobre comandos core
   */
  discoverCoreCommands(): Command[] {
    const commands: Command[] = [];
    const coreCommandsDir = path.join(this.onionRoot, 'core', 'commands');
    
    if (!fs.existsSync(coreCommandsDir)) {
      return commands;
    }
    
    const files = fs.readdirSync(coreCommandsDir);
    files.forEach(file => {
      if (file.endsWith('.md')) {
        commands.push({
          name: file.replace('.md', ''),
          path: path.join(coreCommandsDir, file),
          context: 'core',
          level: 'core',
          relativePath: path.relative(this.projectRoot, path.join(coreCommandsDir, file))
        });
      }
    });
    
    return commands;
  }

  /**
   * Descobre agentes core
   */
  discoverCoreAgents(): Agent[] {
    const agents: Agent[] = [];
    const coreAgentsDir = path.join(this.onionRoot, 'core', 'agents');
    
    if (!fs.existsSync(coreAgentsDir)) {
      return agents;
    }
    
    const files = fs.readdirSync(coreAgentsDir);
    files.forEach(file => {
      if (file.endsWith('.md')) {
        agents.push({
          name: file.replace('.md', ''),
          path: path.join(coreAgentsDir, file),
          context: 'core',
          relativePath: path.relative(this.projectRoot, path.join(coreAgentsDir, file))
        });
      }
    });
    
    return agents;
  }

  /**
   * Descobre todos os recursos
   */
  discover(): OnionResources {
    if (!this.config) {
      this.loadConfig();
    }
    
    const contexts = this.discoverContexts();
    const commands: Command[] = [];
    const agents: Agent[] = [];
    
    // Comandos e agentes core
    commands.push(...this.discoverCoreCommands());
    agents.push(...this.discoverCoreAgents());
    
    // Comandos e agentes por contexto
    contexts.forEach(context => {
      commands.push(...this.discoverCommands(context));
      agents.push(...this.discoverAgents(context));
    });
    
    return {
      config: this.config!,
      contexts,
      commands,
      agents
    };
  }

  /**
   * Gera windsurf.config.yml
   */
  async generateConfig(): Promise<void> {
    const resources = this.discover();
    const configPath = path.join(this.projectRoot, 'windsurf.config.yml');
    
    // Mapear comandos para formato Windsurf
    const windsurfCommands = resources.commands.map(cmd => ({
      name: cmd.context === 'core' ? cmd.name : `${cmd.context}/${cmd.name}`,
      path: cmd.relativePath,
      context: cmd.context,
      level: cmd.level,
      description: `Onion command: ${cmd.context}/${cmd.name} (${cmd.level})`
    }));
    
    // Mapear agentes para formato Windsurf
    const windsurfAgents = resources.agents.map(agent => ({
      name: agent.context === 'core' ? agent.name : `${agent.context}/${agent.name}`,
      path: agent.relativePath,
      context: agent.context,
      description: `Onion agent: ${agent.context}/${agent.name}`
    }));
    
    // Gerar config YAML
    const windsurfConfig = {
      onion: {
        version: '4.0.0-beta.1',
        generated: new Date().toISOString(),
        contexts: resources.contexts,
        commands: windsurfCommands,
        agents: windsurfAgents
      },
      // Estrutura para Windsurf IDE
      commands: windsurfCommands.map(cmd => ({
        name: cmd.name,
        path: cmd.path,
        metadata: {
          context: cmd.context,
          level: cmd.level,
          description: cmd.description
        }
      })),
      agents: windsurfAgents.map(agent => ({
        name: agent.name,
        path: agent.path,
        metadata: {
          context: agent.context,
          description: agent.description
        }
      }))
    };
    
    const yamlContent = yaml.stringify(windsurfConfig, {
      indent: 2,
      lineWidth: 0
    });
    
    fs.writeFileSync(configPath, yamlContent, 'utf-8');
    console.log(`✅ Generated windsurf.config.yml with ${resources.commands.length} commands and ${resources.agents.length} agents`);
  }
}

// Singleton instance
let bridgeInstance: WindsurfOnionBridge | null = null;

export function getBridge(projectRoot?: string): WindsurfOnionBridge {
  if (!bridgeInstance) {
    bridgeInstance = new WindsurfOnionBridge(projectRoot || process.cwd());
  }
  return bridgeInstance;
}

// Auto-executar se chamado diretamente
if (require.main === module) {
  const bridge = getBridge();
  bridge.generateConfig().catch(err => {
    console.error('❌ Error generating Windsurf config:', err);
    process.exit(1);
  });
}
