onion:
  version: 4.0.0-beta.1
  generated: 2026-01-01T16:34:05.060Z
  contexts:
    - business
  commands:
    - name: help
      path: .onion/core/commands/help.md
      context: core
      level: core
    - name: business/spec
      path: .onion/contexts/business/commands/starter/spec.md
      context: business
      level: starter
  agents:
    - name: business/product-agent
      path: .onion/contexts/business/agents/product-agent.md
      context: business
commands:
  - name: help
    path: .onion/core/commands/help.md
    metadata:
      context: core
      level: core
  - name: business/spec
    path: .onion/contexts/business/commands/starter/spec.md
    metadata:
      context: business
      level: starter
agents:
  - name: business/product-agent
    path: .onion/contexts/business/agents/product-agent.md
    metadata:
      context: business
